name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: mkdir bin;cd bin;cmake -DCMAKE_BUILD_TYPE=Debug/Release  -DADD_THIRD_PARTY="ON" ..;make;make install;cd ../demo;mkdir bin;cd bin;cmake ..;make
