name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: create bin dir
      run: mkdir bin
    - name: change to bin dir
      run: cd bin
    - name: test freetype
      run: sh ../build/auto_build_freetype.sh
